project:
  type: website
  render:
    - "labs/00_lab/setup.qmd"
    - schedule.qmd
    - "*.qmd"
    - "!labs/00_lab/renv/"
    - "!renv/"
    - "!images/"
    - "!styles/"
    - "!site_libs/"

website:
  page-navigation: true
  title: "MLBA - S24 "
  description: "Homepage for Machine Learning in Business Analytics at HEC Lausanne, Spring 2024."
  site-url: "https://do-unil.github.io/mlba"
  favicon: images/logo.dark.png
  repo-url: https://github.com/do-unil/mlba
  repo-actions: [source, issue]
  open-graph: true

  sidebar:
    # background: "#798b93"
    logo: "images/logo.light.png"
    pinned: true
    alignment: center
    tools:
      - icon: person-rolodex
        text: Moodle
        href: http://moodle2.unil.ch/course/view.php?id=8715
      - icon: github
        text: GitHub Repo
        href: https://github.com/do-unil/mlba

    style: docked
    search: true
    collapse-level: 1
    lightbox: true

    contents:
      - section: "Course information"
        contents:
          - href: index.qmd
            text: Overview
          - href: schedule.qmd
            text: Schedule
          # - href: links.qmd
          #   text: Useful links
          - href: references.qmd
            text: References
          - href: faq.qmd
            text: FAQ
      - section: "Lectures"
        contents:
          - href: "lectures/01_Introduction/ML_Intro.qmd"
            text: "Intro to ML"
          - href: "lectures/02_DataExploration/ML_DataExplo.qmd"
            text: "Data Exploration"
          - href: "lectures/03_Models/030_Introduction/ML_Models_Intro.qmd"
            text: "Intro to Models"
          - href: "lectures/03_Models/031_LinearLogisticRegression/ML_LinLogReg.qmd"
            text: "Linear & Logistic Regression"
          - href: "lectures/03_Models/032_Trees/ML_Trees.qmd"
            text: "Decision Trees"
          - href: "lectures/03_Models/033_NeuralNetworks/ML_NN.qmd"
            text: "Neural Networks"
          - href: "lectures/03_Models/034_SupportVectorMachine/ML_SVM.qmd"
            text: "Support Vector Machines"
          - href: "lectures/04_Metrics/ML_Metrics.qmd"
            text: "Metrics"
          - href: "lectures/05_DataSplitting/ML_DataSplitting.qmd"
            text: "Data Splitting"
          - href: "lectures/06_Ensembles/ML_Ensemble.qmd"
            text: "Ensemble Methods"
          - href: "lectures/07_InterpretableML/ML_Interp.qmd"
            text: "Interpretable ML"
          - href: "lectures/08_UnsupervisedLearning/080_Introduction/ML_UnsupIntro.qmd"
            text: "Intro to Unsuperised Learning"
          - href: "lectures/08_UnsupervisedLearning/081_Clustering/ML_Clustering.qmd"
            text: "Clustering"
          - href: "lectures/08_UnsupervisedLearning/082_DimensionReduction/ML_DimRed.qmd"
            text: "Dimension Reduction"
      - section: "Labs"
        contents:
          - href: labs/00_lab/setup.qmd
            text: "Setup"
          - href: labs/03_Models/031_LinearLogisticRegression/Ex_ML_LinLogReg.qmd
            text: "Linear & Logistic Regression"
          - href: labs/03_Models/032_Trees/Ex_ML_Tree.qmd
            text: "Decision Trees"
          - href: labs/03_Models/033_NeuralNetworks/EX_ML_NN.qmd
            text: "Neural Networks"
          - href: labs/03_Models/034_SupportVectorMachine/Ex_ML_SVM.qmd
            text: "Support Vector Machines"
          # - href: labs/03_Models/035_KNN/Ex_ML_KNN.qmd
          #   text: "K-Nearest Neighbors"
          - href: labs/04_Metrics/Ex_ML_Scoring.qmd
            text: "Metrics"
          - href: labs/05_DataSplitting/Ex_ML_Data_Splitting.qmd
            text: "Data Splitting"
          - href: labs/06_Ensembles/Ex_ML_Ensemble.qmd
            text: "Ensemble Methods"
          - href: labs/07_InterpretableML/Ex_ML_VarImp.qmd
            text: "Interpretable ML"
          - href: labs/08_UnsupervisedLearning/081_Clustering/Ex_ML_Clustering.qmd
            text: "Clustering"
          - href: labs/08_UnsupervisedLearning/082_DimensionReduction/Ex_ML_PCA.qmd
            text: "PCA"
          - href: labs/08_UnsupervisedLearning/083_AutoEncoders/Ex_ML_Autoencoder.qmd
            text: "Autoencoders"
      - section: "Assessments"
        contents:
          - href: assessments/exam.qmd
            text: Exam
          - section: "Project"
            contents:
              - href: assessments/Project_Directives.qmd
                text: Project Directives
              - href: assessments/Proposal_guidelines.qmd
                text: Proposal Guidelines
              - href: assessments/Report_Guideline.qmd
                text: Report Guidelines
              - href: assessments/Presentation_Guidelines.qmd
                text: Presentation Guidelines              
          # - href: assessments/project.qmd
          #   text: Project
      # - href: resources.qmd
      #   text: Resources

  page-footer:
    right: "This page is built with 🤍 and [Quarto](https://quarto.org/)."
    left: "&copy; Copyright 2024, [Ilia Azizi & Marc-Olivier Boldi](https://iliaazizi.com/)"
    background: "#0086CA"

  # navbar: 
  #   background: "#0086CA"


format:
  html:
    highlight-style: breeze
    theme:
      light: [cosmo, style/mlba.scss]
      dark: [cosmo, style/mlba.scss,style/dark.scss]
    linkcolor: "#798b93"
    toc: true
    code-copy: true
    code-overflow: wrap
    mainfont: "Atkinson Hyperlegible"
    # monofont: 'Fira Code'

    # This script changes the image src depending on the body class (quarto-light or quarto-dark). We primarly use it to change the logo in the navbar.
    include-before-body:
      - text: |
          <script type="application/javascript">
          // Description: Change image src depending on body class (quarto-light or quarto-dark)
          function updateImageSrc() {
            var bodyClass = window.document.body.classList;
            var images = window.document.getElementsByTagName('img');
            for (var i = 0; i < images.length; i++) {
              var image = images[i];
              var src = image.src;
              var newSrc = src;
              if (bodyClass.contains('quarto-light') && src.includes('.dark')) {
                newSrc = src.replace('.dark', '.light');
              } else if (bodyClass.contains('quarto-dark') && src.includes('.light')) {
                newSrc = src.replace('.light', '.dark');
              }
              if (newSrc !== src) {
                image.src = newSrc;
              }
            }
          }

          var observer = new MutationObserver(function(mutations) {
            mutations.forEach(function(mutation) {
              if (mutation.type === 'attributes' && mutation.attributeName === 'class') {
                updateImageSrc();
              }
            });
          });

          observer.observe(window.document.body, {
            attributes: true
          });

          updateImageSrc();
          </script>
    html-math-method: mathjax
    code-tools: true
    code-fold: false
    code-link: true
    embed-resources: false

execute:
  freeze: auto
  warning: false
  message: false
  output: false

# editor: visual
