---
title: "Exam"
format: 
    html:
        code-tools: false
        code-link: false
---

[Mock Exam 2024 📄](Mock_2024.pdf)

**Directives for the 2026 exam (please read carefully):**

<!-- - Room Internef 126 from 9:00 to 11:00. Be there at least 15 minutes before! -->
- Details (Room, hour) TBA. Be there at least 15 minutes before!
- In-class presence mandatory and controlled.
- Exam on laptop (make sure you have enough battery!) and moodle exam.
- Open questions answered in text on moodleexam (essay format).
- Connection to a dedicated wifi.
- Open documents: you can bring any numerical and printed documents. !! No internet access outside the dedicated wifi. Bring documents locally (no cluster). Use USB Key for security.
- During the exam, no communication allowed (WhatsApp, emails, etc.) and no internet access (google search, AI agent, etc.), except to access moodleexam
- During the exam: NO QUESTION (except technical issues). You have enough space to explain and write the context.