---
title: "Presentation Guidelines"
format: 
  html: default
  pdf: default
execute: 
  freeze: false
  output: true
code-tools: false
code-link: false
---

::: {.callout-important}
## ATTENTION
🏗 *This section is still under development (to be updated soon)* 🏗
:::

## Some Guidelines For A Presentation

A typical plan: 

- Title, date and team 
- Context 
- Agenda  
- Data description 
- Methodology 
- Results 
- Conclusion and discussion 
- References if needed 
- "Thank you + Any Question" slide 

Material:

- 1-3 minutes per slide (e.g., around 10 to 20 slides for a 30-minutes presentation with only slides). 
- Keep additional slides hidden (typical technical ones, extra results, etc.) and show them in case of questions/discussion. 
- Consider also live demo, showing codes, etc.  
 
Organization: 

- In group, define clearly who is going to explain what.  
- Make fluent transition (useless to start over again the context when the speaker change). 

Walk away from these guidelines if they are not adapted in your case. Also, feel free to let your originality speaks. The further guidelines below are based on the [following link](https://www.elsevier.com/connect/how-to-give-a-dynamicscientific-presentation):

### Know Your Audience

Adapt your speech to your audience. If people think often about adapting the technical content, it is equally important to adapt the context. Including a deep explanation of a context to an audience who knows it can be as counter-productive and time consuming as not explaining this context when it is due. 

2. Tell audience members up front why they should care and what is in it for them Explain the issue and why it is important. 

3. Convey your excitement If any… but do not overplay this. 

4. Build a story 
a. Explain the context b. Frame the problem c. Provide highlights: some parts in the analysis/project were striking and determinant. Find 
and explain these key points. 
d. Conclude by summing up key points and open to new area, problems, etc. 
 
5. Keep it simple Depending on your audience, some terms may be difficult to understand. If you use difficult terms, you will not impress the audience, you will annoy them. 

6. Prepare, prepare, prepare 
a. Set the stage (equipment ready, have a charger in case, have your headphone ready, etc.) b. Get ready (concentrate and calm down, breathe, visualize) 
 

7. Speak up, talk to the audience (not to the screen) 
 

8. Start and finish on time  
Nothing worse than a late presentation. If you need more time, mention it during the presentation and apologize, before to end of the presentation. 

9. Do not drift at the end The end of your presentation should be clear. Do not start a new conversation. For the slides/support materials 

## 1. Less Is More

Though, it is difficult to gives a general rule, a regular slide (not the title or the "Thank you. Any Question?" 
slide) is 1 to 3 minutes. Thus, a 30 minutes presentation cannot have more than 30 slides, and it is already very long. If you are afraid to miss something, have some extra slides with the details that you may show if anyone has a question about it. 

2. Create sections Pretty much like the report. It is especially important for group presentation that must be well structured. 

3. Avoid clutter 
A slide should be light and easy to read. It is a support for your speech. It is not to be read in detail neither by you nor by the audience. 

4. Make it readable 
It is useless to bold or to capitalize every word. Use one appropriate and coherent font. An incomprehensible slide does not become comprehensible or joyful if written in colors. 

5. Use visual Consider using image, figures, etc. "A drawing is worth a thousand words". Of course, this is not an objective. Always choose the best way to convey information. If an image is only here to be "nice", prefer words. 

6. Check your spelling 
We all make typos, especially when it is not our mother tongue. But having too many misspelled words on 20 slides with few words will make you lose credibility. Use correctors, re-read and re-read, ask for help, etc. 