on:
  push:
    branches: main
  workflow_dispatch:

name: Build Site

permissions:
  contents: write

jobs:
  build-website:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Quarto CLI
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          tinytex: true

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libxml2-dev libssl-dev

      - name: Publish Quarto Project
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages