on:
  push:
    branches: main
  pull_request:
    branches: main
  workflow_dispatch:

name: Build Site

permissions:
  contents: write
  pages: write

jobs:
  build-website:
    runs-on: ubuntu-latest
    concurrency:
      group:  ${{ github.workflow }}
      cancel-in-progress: true
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      # Add R_MAX_VSIZE to increase memory limit
      R_MAX_VSIZE: 100Gb
    steps:
      - uses: actions/checkout@v3

      - name: Install Quarto CLI
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          tinytex: true
          # version: 1.4.330

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libglu1-mesa-dev libxml2-dev libssl-dev libv8-dev libfontconfig1-dev libfreetype6-dev cmake libmagick++-dev libpoppler-cpp-dev tesseract-ocr libtesseract-dev
  
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true     

      # See here for more info https://github.com/r-lib/actions/tree/v2-branch/setup-renv
      - name: Set up renv
        uses: r-lib/actions/setup-renv@v2
        with:
          cache-version: 3

      # Modify R's memory limits
      - name: Configure R memory limits
        run: |
          echo "options(java.parameters = '-Xmx16000m')" >> ~/.Rprofile
          echo "options(future.globals.maxSize = 8 * 1024^3)" >> ~/.Rprofile
          echo "options(future.rng.onMisuse='ignore')" >> ~/.Rprofile

      # Increase system limits
      - name: Increase system limits
        run: |
          ulimit -s unlimited
          # Set higher memory limits
          sudo sysctl -w vm.max_map_count=262144
          # Display limits for verification
          ulimit -a

      # Create a custom .Renviron file to set R_MAX_VSIZE
      - name: Set R environment variables
        run: |
          echo "R_MAX_VSIZE=100Gb" > ~/.Renviron
          echo "R_MAX_MEM_SIZE=100Gb" >> ~/.Renviron

      # Render with specific options to avoid stack issues
      - name: Publish Quarto Project
        run: |
          # Set R_MAX_NUM_DLLS to a higher value
          export R_MAX_NUM_DLLS=1000
          # Use Rscript to set memory limits before rendering
          Rscript -e 'options(expressions = 500000); options(max.print = 1000); options(scipen = 999); options(width = 120); options(future.globals.maxSize = 8 * 1024^3); quarto::quarto_render(".", as_job = FALSE)'
          
      - name: Deploy 🚀
        if: github.event_name != 'pull_request'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: _site # The folder the action should deploy.