on:
  push:
    branches: main
  pull_request:
    branches: main
  workflow_dispatch:

name: Build Site

permissions:
  contents: write
  pages: write

jobs:
  build-website:
    runs-on: windows-latest
    concurrency:
      group: ${{ github.workflow }}
      cancel-in-progress: true
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      # Configure R to use more memory
      R_MAX_MEM_SIZE: 16000M
      R_MAX_VSIZE: 16000M
      # Increase this value significantly
      R_C_STACK_SIZE: 256M
    steps:
      - uses: actions/checkout@v3

      - name: Install Quarto CLI
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          tinytex: true
          # version: 1.4.330

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: 3.9
          activate-environment: mlba
          miniconda-version: "latest"
          
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
          windows-path-include-mingw: true

      # See here for more info https://github.com/r-lib/actions/tree/v2-branch/setup-renv
      - name: Set up renv
        uses: r-lib/actions/setup-renv@v2
        with:
          cache-version: 3
      
      # Configure memory settings for R on Windows
      - name: Configure R memory settings
        run: |
          echo "R_MAX_MEM_SIZE=16000M" | Out-File -FilePath $env:GITHUB_ENV -Append
          echo "R_MAX_VSIZE=16000M" | Out-File -FilePath $env:GITHUB_ENV -Append
          # Display memory information
          Get-CimInstance Win32_OperatingSystem | Select-Object TotalVisibleMemorySize,FreePhysicalMemory
      
      - name: Create CI-specific config
        shell: pwsh
        run: |
          # Create a temporary Quarto config for CI that skips Python setup steps
          $configContent = @"
          execute:
            freeze: auto
            error: false
            eval: true
            echo: true
            warning: true
            fig-dpi: 96
            timeout: 600
          "@
          
          # Create a file-specific config only for setup.qmd
          New-Item -Path "labs/00_lab" -Name "_ci-setup.yml" -ItemType File -Force
          Set-Content -Path "labs/00_lab/_ci-setup.yml" -Value $configContent

      - name: Publish Quarto Project
        shell: pwsh
        run: |
          # Configure maximum stack limits
          [System.Threading.Thread]::CurrentThread.MaximumStackSize = [int]::MaxValue
          
          # Render with quarto publish using the CI-specific config
          quarto publish gh-pages --no-prompt
        env:
          R_C_STACK_SIZE: 256M

      - name: Deploy 🚀
        if: github.event_name != 'pull_request'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: _site # The folder the action should deploy.