on:
  push:
    branches: main
  pull_request:
    branches: main
  workflow_dispatch:

name: Build Site

permissions:
  contents: write
  pages: write

jobs:
  build-website:
    # Switch to Windows runner
    runs-on: windows-latest
    concurrency:
      group: ${{ github.workflow }}
      cancel-in-progress: true
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      # Add R-specific memory settings
      R_MAX_VSIZE: 16Gb
      R_MAX_NUM_DLLS: 250
    steps:
      - uses: actions/checkout@v3

      - name: Install Quarto CLI
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          tinytex: true

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true     

      # See here for more info https://github.com/r-lib/actions/tree/v2-branch/setup-renv
      - name: Set up renv
        uses: r-lib/actions/setup-renv@v2
        with:
          cache-version: 3

      - name: Configure R memory settings
        shell: bash
        run: |
          mkdir -p ~/.R
          echo "R_MAX_VSIZE=16Gb" >> ~/.Renviron
          echo "R_MAX_NUM_DLLS=250" >> ~/.Renviron
          echo "R_C_STACK_SIZE=64M" >> ~/.Renviron
          Rscript -e "options(java.parameters = '-Xmx8g')"
          Rscript -e "options(future.globals.maxSize = 8 * 1024^3)"
          Rscript -e "options(expressions = 500000)"

      - name: Render Problematic Files
        shell: bash
        run: |
          # Try rendering the problematic file with special settings
          Rscript -e "options(expressions = 500000); options(max.print = 1000)" -e "rmarkdown::render('labs/00_lab/setup.qmd', output_format = 'html_document')"
          
      - name: Publish Quarto Project
        shell: bash
        env:
          QUARTO_DENO_V8_OPTIONS: --max-old-space-size=16384
        run: |
          quarto render --profile gh-pages
          quarto publish --server gh-pages --id gh-pages --no-render

      - name: Deploy 🚀
        if: github.event_name != 'pull_request'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: _site